[[constraint]]
  name = "github.com/trimmer-io/go-timecode"
  # required for build to work
  revision = "652b5c4cae11abde9bdc44cd5ba9cf1bfcd06a1a"
  source = "https://github.com/crushedpixel/go-timecode.git"

[[constraint]]
  name = "github.com/schollz/progressbar"
  # required for color codes and Clear() features
  revision = "cc61d3b564829f7a41e66e10b8154c8a0199274e"

[[constraint]]
  name = "github.com/satori/go.uuid"
  revision = "36e9d2ebbde5e3f13ab2e25625fd453271d6522e"
